version: '3.8'
services:
  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  server-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=JAISL_104911_!?

  neo4j:
      image: neo4j:latest
      ports:
        - "7474:7474"
        - "7687:7687"
      environment:
        NEO4J_AUTH: neo4j/JAISL_104911_!?
      volumes:
        - ./neo4j/data:/data
        - ./neo4j/logs:/logs
        - ./neo4j/import:/var/lib/neo4j/import
        - ./neo4j/plugins:/plugins
